services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: someuser
      MONGO_INITDB_ROOT_PASSWORD: somepassword

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: someuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: somepassword
      ME_CONFIG_MONGODB_URL: mongodb://someuser:somepassword@mongo:27017/